inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
    - bin/**/*

# front comment of class and module
Style/Documentation:
  Enabled: false

# Jananese comment
Style/AsciiComments:
  Enabled: false

# line length
Layout/LineLength:
  Max: 120

# line length of block
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*


# from error message
