inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - db/**/*
    - vendor/**/*

# front comment of class and module
Documentation:
  Enabled: false

# Jananese comment
Style/AsciiComments:
  Enabled: false

# line length
Metrics/LineLength:
  Max: 120

# line length of block
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
